# CatSero v3 配置文件
## 配置文件文档请参阅：
## https://docs.ovome.icu/CatSero/config/

# 插件本体配置
[plugin]
# 接受bStats统计
allow-bstats = true

# 插件更新设置
[update]
# 是否启用
enable = true
# 要从哪里拉取版本信息
# 一般情况下无需修改
update-server = "https://api.huahuo-cn.tk/mcplugins/CatSero/version"