name: CatSero
main: moe.xmcn.catsero.v3.CatSero
description: 基于MiraiMC的Minecraft功能插件
version: @plugin.version@
api-version: 1.13
authors:
  - XiaMoHuaHuo_CN
  - The Love ❤
softdepend:
  - MiraiMC
  - PlaceholderAPI
  - TrChat
libraries:
  - "org.jetbrains.kotlin:kotlin-stdlib:1.8.22"
  - "com.alibaba:fastjson:2.0.34"
  - "org.tomlj:tomlj:1.1.0"
  - "com.squareup.okhttp3:okhttp:4.11.0"
commands:
  catsero:
    description: "CatSero 基础方法"
    usage: "/catsero <version|reload|whitelist|cms>"
    subcommands:
      version:
        description: "插件版本以及信息"

permissions:
  catsero.*:
    description: "CatSero所有权限组"
    default: false
    children:
      catsero.admin:
        description: "CatSero OP权限组"
        default: op
