# CatSero v3 功能配置文件
## 配置文件文档请参阅：
## https://docs.ovome.icu/CatSero/config/

[general]
timeFormat = "HH:mm:ss, yyyy-MM-dd"

# 聊天转发
[chatForward]
# 是否启用该功能
enable = false
# Bot定义
mirai = ["geKo", "hikari"]
# 屏蔽词
[chatForward.filter]
# 是否启用该功能
enable = false
# 替换成的字符
replace = "**"
# 本地屏蔽词
[chatForward.filter.local]
# 启用该功能
enable = false
# 本地屏蔽词文件列表
# 请填写文件绝对路径
localFiles = []
# 远程屏蔽词
[chatForward.filter.remote]
# 是否启用该功能
enable = false
# 远程屏蔽词列表
# 此处使用的是TrChat的默认远程源
# 感谢 @南城 提供的词库(已改为Jsdelivr CDN)
remoteUrls = [
    "https://fastly.jsdelivr.net/gh/Yurinann/Filter-Thesaurus-Cloud@main/database.json"
]
# 自动更新源
[chatForward.filter.autoUpdate]
# 是否启用该功能
enable = true
# 更新间隔
interval = 300
