name: b-dev Gradle - Pull Request Check

on:
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3.9.0
        with:
          java-version: '11'
          distribution: 'zulu'

      - name: Test Build with Gradle
        run: ./gradlew build
